version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    working_dir: "/home/supporters_hackathon2022_vol8"
    volumes:
      - "./:/home/supporters_hackathon2022_vol8"
      - node_modules_volume:/home/supporters_hackathon2022_vol8/frontend/node_modules
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    working_dir: "/home/supporters_hackathon2022_vol8"
    volumes:
      - "./:/home/supporters_hackathon2022_vol8"
    tty: true
    environment:
      - HOST=0.0.0.0
volumes:
  node_modules_volume:

